from enum import Enum


class EventType(Enum):
    EHR_GENERATED = "EHR_GENERATED"
    EHR_INTEGRATED = "EHR_INTEGRATED"
    EHR_REQUESTED = "EHR_REQUESTED"
    EHR_SENT = "EHR_SENT"
    EHR_VALIDATED = "EHR_VALIDATED"
    ERROR = "ERROR"
    PDS_GENERAL_UPDATE = "PDS_GENERAL_UPDATE"
    REGISTRATION_STARTED = "REGISTRATION_STARTED"
    SDS_LOOKUP = "SDS_LOOKUP"
    PDS_TRACE = "PDS_TRACE"
    EHR_READY_TO_INTEGRATE = "EHR_READY_TO_INTEGRATE"
    MIGRATE_DOCUMENT_REQUEST = "MIGRATE_DOCUMENT_REQUEST"
    MIGRATE_DOCUMENT_RESPONSE = "MIGRATE_DOCUMENT_RESPONSE"
    MIGRATE_STRUCTURED_RECORD_REQUEST = "MIGRATE_STRUCTURED_RECORD_REQUEST"
    MIGRATE_STRUCTURED_RECORD_RESPONSE = "MIGRATE_STRUCTURED_RECORD_RESPONSE"
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER"
