from enum import Enum


class EventType(Enum):
    EHR_GENERATED = ("EHR_GENERATED",)
    EHR_INTEGRATED = ("EHR_INTEGRATED",)
    EHR_REQUESTED = ("EHR_REQUESTED",)
    EHR_SENT = "EHR_SENT"
    EHR_VALIDATED = "EHR_VALIDATED"
    ERROR = "ERROR"
    PDS_GENERAL_UPDATE = "PDS_GENERAL_UPDATE"
    REGISTRATION_STARTED = "REGISTRATION_STARTED"
    SDS_LOOKUP = "SDS_LOOKUP"
    PDS_TRACE = "PDS_TRACE"
